In [1]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

/Users/naimsassine/.pyenv/versions/3.7.3/lib/python3.7/site-packages/pandas/compat/__init__.py:97: UserWarning: Could not import the lzma module. Your installed Python is incomplete. Attempting to use lzma compression will result in a RuntimeError.
  warnings.warn(msg)


In [2]:
layer = layers.Dense(3)

In [3]:
layer.weights

[]

In [4]:
x = tf.ones((1,4))

In [5]:
x

<tf.Tensor: shape=(1, 4), dtype=float32, numpy=array([[1., 1., 1., 1.]], dtype=float32)>

In [6]:
y = layer(x)
layer.weights

[<tf.Variable 'dense/kernel:0' shape=(4, 3) dtype=float32, numpy=
 array([[ 0.25137377, -0.8629391 ,  0.2742324 ],
        [ 0.43978322,  0.39257252, -0.16895193],
        [-0.29957557,  0.54238284, -0.4965844 ],
        [ 0.3242606 ,  0.8143976 , -0.08226067]], dtype=float32)>,
 <tf.Variable 'dense/bias:0' shape=(3,) dtype=float32, numpy=array([0., 0., 0.], dtype=float32)>]

In [7]:
layer.summary()

AttributeError: 'Dense' object has no attribute 'summary'

In [17]:
z = tf.ones((1,5))

In [19]:
layer(z)

ValueError: Input 0 of layer "dense" is incompatible with the layer: expected axis -1of input shape to have value 4, but received input with shape (1, 5)

In [8]:
dense = tf.keras.Sequential([
    tf.keras.layers.Dense(units=64, activation='relu'),
    tf.keras.layers.Dense(units=64, activation='relu'),
    tf.keras.layers.Dense(units=1)
])

In [9]:
y = dense(x)

In [13]:
dense.weights

[<tf.Variable 'dense_1/kernel:0' shape=(4, 64) dtype=float32, numpy=
 array([[-0.13683464, -0.24619743, -0.08687554,  0.09135842, -0.06195062,
         -0.08483541,  0.15032962,  0.22918934,  0.04392558,  0.05871525,
         -0.28308308,  0.04313719, -0.10938695,  0.29593253,  0.21608478,
         -0.1382466 , -0.2650159 , -0.201215  , -0.20999728, -0.2709093 ,
          0.22886384,  0.28718537, -0.03115907, -0.0339756 ,  0.23834676,
         -0.1553531 ,  0.01284662, -0.15810144, -0.0631371 ,  0.2808296 ,
          0.24881846,  0.02217287,  0.11506543,  0.0910112 , -0.05327542,
          0.17834339, -0.19126707,  0.07411009,  0.0778915 ,  0.17985061,
         -0.17590758, -0.02010626, -0.01539963, -0.20400342,  0.0858162 ,
          0.14076677,  0.27380276,  0.1581425 , -0.19987896, -0.16171925,
         -0.21503228, -0.13264503,  0.15063953,  0.21605474,  0.28901118,
         -0.06123109, -0.02831   ,  0.15258753, -0.24474087,  0.06928018,
          0.26175612, -0.14405866, -0.05326